definitions: {}
info:
  description: powered by Flasgger
  termsOfService: /tos
  title: My API
  version: 0.0.1
paths:
  /api/items:
    get:
      responses:
        '200':
          description: A list of items
          schema:
            properties:
              items:
                items:
                  type: string
                type: array
            type: object
      summary: Example endpoint returning a list of items.
      tags:
      - items
swagger: '2.0'
